info:
  namespace: pamhc2foodcore

categories:
  pamhc2foodcore:
    enabled: true
    name: display-category-name-foodcore
    icon: pamhc2foodcore:baconandeggsitem
    items:
    - pamhc2foodcore:applejellyitem
    - pamhc2foodcore:applejellytoastitem
    - pamhc2foodcore:applejuiceitem
    - pamhc2foodcore:applepieitem
    - pamhc2foodcore:applesauceitem
    - pamhc2foodcore:applesmoothieitem
    - pamhc2foodcore:appleyogurtitem
    - pamhc2foodcore:baconandeggsitem
    - pamhc2foodcore:baconcheeseburgeritem
    - pamhc2foodcore:bakedvegetablemedlyitem
    - pamhc2foodcore:basiccheeseburgeritem
    - pamhc2foodcore:basicchickensandwichitem
    - pamhc2foodcore:basicfishsandwichitem
    - pamhc2foodcore:basichamburgeritem
    - pamhc2foodcore:batteritem
    - pamhc2foodcore:beefjerkyitem
    - pamhc2foodcore:boiledeggitem
    - pamhc2foodcore:butteredbakedpotatoitem
    - pamhc2foodcore:butteritem
    - pamhc2foodcore:caramelappleitem
    - pamhc2foodcore:caramelcupcakeitem
    - pamhc2foodcore:caramelicecreamitem
    - pamhc2foodcore:caramelitem
    - pamhc2foodcore:caramelmuffinitem
    - pamhc2foodcore:caramelyogurtitem
    - pamhc2foodcore:carrotbreaditem
    - pamhc2foodcore:carrotcakeitem
    - pamhc2foodcore:carrotcupcakeitem
    - pamhc2foodcore:carrotmuffinitem
    - pamhc2foodcore:carrotsoupitem
    - pamhc2foodcore:cheesecakeitem
    - pamhc2foodcore:cheeseitem
    - pamhc2foodcore:chickendinneritem
    - pamhc2foodcore:chickenjerkyitem
    - pamhc2foodcore:chickennuggetitem
    - pamhc2foodcore:chickenpotpieitem
    - pamhc2foodcore:chocolatebaconitem
    - pamhc2foodcore:chocolatebaritem
    - pamhc2foodcore:chocolatecakeitem
    - pamhc2foodcore:chocolatecaramelfudgeitem
    - pamhc2foodcore:chocolatecupcakeitem
    - pamhc2foodcore:chocolatedonutitem
    - pamhc2foodcore:chocolateicecreamitem
    - pamhc2foodcore:chocolatemilkitem
    - pamhc2foodcore:chocolatemilkshakeitem
    - pamhc2foodcore:chocolatemuffinitem
    - pamhc2foodcore:chocolatepuddingitem
    - pamhc2foodcore:chocolaterollitem
    - pamhc2foodcore:chocolateyogurtitem
    - pamhc2foodcore:cocoapowderitem
    - pamhc2foodcore:cookedgroundbeefitem
    - pamhc2foodcore:cookedgroundchickenitem
    - pamhc2foodcore:cookedgroundfishitem
    - pamhc2foodcore:cookedgroundmuttonitem
    - pamhc2foodcore:cookedgroundporkitem
    - pamhc2foodcore:cookedgroundrabbititem
    - pamhc2foodcore:cookiesandmilkitem
    - pamhc2foodcore:cookingoilitem
    - pamhc2foodcore:cottoncandyitem
    - pamhc2foodcore:crackeritem
    - pamhc2foodcore:creamitem
    - pamhc2foodcore:donutitem
    - pamhc2foodcore:doughitem
    - pamhc2foodcore:epicbaconitem
    - pamhc2foodcore:fishandchipsitem
    - pamhc2foodcore:fishjerkyitem
    - pamhc2foodcore:fishsticksitem
    - pamhc2foodcore:flouritem
    - pamhc2foodcore:freshmilkitem
    - pamhc2foodcore:freshwateritem
    - pamhc2foodcore:friedchickenitem
    - pamhc2foodcore:friedeggitem
    - pamhc2foodcore:friesitem
    - pamhc2foodcore:fruitcrumbleitem
    - pamhc2foodcore:fruitpunchitem
    - pamhc2foodcore:fruitsaladitem
    - pamhc2foodcore:glazedcarrotsitem
    - pamhc2foodcore:glowberryjellyitem
    - pamhc2foodcore:glowberryjellytoastitem
    - pamhc2foodcore:glowberryjuiceitem
    - pamhc2foodcore:glowberrypieitem
    - pamhc2foodcore:glowberrysmoothieitem
    - pamhc2foodcore:glowberryyogurtitem
    - pamhc2foodcore:grilledcheeseitem
    - pamhc2foodcore:groundbeefitem
    - pamhc2foodcore:groundchickenitem
    - pamhc2foodcore:groundfishitem
    - pamhc2foodcore:groundmuttonitem
    - pamhc2foodcore:groundporkitem
    - pamhc2foodcore:groundrabbititem
    - pamhc2foodcore:gummybearsitem
    - pamhc2foodcore:hotchocolateitem
    - pamhc2foodcore:hotdogitem
    - pamhc2foodcore:icecreamitem
    - pamhc2foodcore:jellybeansitem
    - pamhc2foodcore:jellydonutitem
    - pamhc2foodcore:macncheeseitem
    - pamhc2foodcore:marshmellowchicksitem
    - pamhc2foodcore:marshmellowsitem
    - pamhc2foodcore:mashedpotatoesitem
    - pamhc2foodcore:mayonaiseitem
    - pamhc2foodcore:meatloafitem
    - pamhc2foodcore:melonjellyitem
    - pamhc2foodcore:melonjellytoastitem
    - pamhc2foodcore:melonjuiceitem
    - pamhc2foodcore:melonsmoothieitem
    - pamhc2foodcore:melonyogurtitem
    - pamhc2foodcore:muttonjerkyitem
    - pamhc2foodcore:noodlesitem
    - pamhc2foodcore:noodlesoupitem
    - pamhc2foodcore:p8juiceitem
    - pamhc2foodcore:pastaitem
    - pamhc2foodcore:pickledbeetsitem
    - pamhc2foodcore:porkjerkyitem
    - pamhc2foodcore:potatochipsitem
    - pamhc2foodcore:potatosaladitem
    - pamhc2foodcore:potatosoupitem
    - pamhc2foodcore:potroastitem
    - pamhc2foodcore:pumpkinbreaditem
    - pamhc2foodcore:pumpkincheesecakeitem
    - pamhc2foodcore:pumpkincupcakeitem
    - pamhc2foodcore:pumpkinmuffinitem
    - pamhc2foodcore:pumpkinsoupitem
    - pamhc2foodcore:pumpkinyogurtitem
    - pamhc2foodcore:rabbitjerkyitem
    - pamhc2foodcore:roastedsunflowerseedsitem
    - pamhc2foodcore:saltitem
    - pamhc2foodcore:scrambledeggitem
    - pamhc2foodcore:smoresitem
    - pamhc2foodcore:softpretzelitem
    - pamhc2foodcore:stewitem
    - pamhc2foodcore:stockitem
    - pamhc2foodcore:sunflowerseedsitem
    - pamhc2foodcore:sweetberryjellyitem
    - pamhc2foodcore:sweetberryjellytoastitem
    - pamhc2foodcore:sweetberryjuiceitem
    - pamhc2foodcore:sweetberrypieitem
    - pamhc2foodcore:sweetberrysmoothieitem
    - pamhc2foodcore:sweetberryyogurtitem
    - pamhc2foodcore:toastitem
    - pamhc2foodcore:trailmixitem
    - pamhc2foodcore:vinegaritem
    - pamhc2foodcore:yogurtitem
    - pamhc2foodcore:hotcoffeeitem
    - pamhc2foodcore:hotnettleteaitem
    - pamhc2foodcore:hotteaitem
    - pamhc2foodcore:roastedacornitem
    - pamhc2foodcore:roastedalmonditem
    - pamhc2foodcore:roastedcashewitem
    - pamhc2foodcore:roastedchestnutitem
    - pamhc2foodcore:roastedhazelnutitem
    - pamhc2foodcore:roastedpecanitem
    - pamhc2foodcore:roastedpinenutitem
    - pamhc2foodcore:roastedpistachioitem
    - pamhc2foodcore:roastedwalnutitem
    - pamhc2foodcore:bakedarrowrootitem
    - pamhc2foodcore:bakedcassavaitem
    - pamhc2foodcore:bakedjicamaitem
    - pamhc2foodcore:bakedparsnipitem
    - pamhc2foodcore:bakedrutabagaitem
    - pamhc2foodcore:bakedsunchokeitem
    - pamhc2foodcore:bakedsweetpotatoitem
    - pamhc2foodcore:bakedtaroitem
    - pamhc2foodcore:bakedturnipitem
    - pamhc2foodcore:bakedwaterchestnutitem