info:
  namespace: pamhc2foodcore
items:
  bakewareitem:
    display_name: display-name-bakewareitem
    durability:
      max_custom_durability: 64
    lore:
    - '&f'
    - 'display-lore-category-name-kitchen'
    resource:
      generate: false
      material: PAPER
      #textures:
      model_path: item/bakewareitem
  cuttingboarditem:
    display_name: display-name-cuttingboarditem
    durability:
      max_custom_durability: 64
    lore:
    - '&f'
    - 'display-lore-category-name-kitchen'
    resource:
      generate: false
      material: PAPER
      #textures:
      model_path: item/cuttingboarditem
  grinderitem:
    display_name: display-name-grinderitem
    durability:
      max_custom_durability: 64
    lore:
    - '&f'
    - 'display-lore-category-name-kitchen'
    resource:
      generate: false
      material: PAPER
      #textures:
      model_path: item/grinderitem
  juiceritem:
    display_name: display-name-juiceritem
    durability:
      max_custom_durability: 64
    lore:
    - '&f'
    - 'display-lore-category-name-kitchen'
    resource:
      generate: false
      material: PAPER
      #textures:
      model_path: item/juiceritem
  mixingbowlitem:
    display_name: display-name-mixingbowlitem
    durability:
      max_custom_durability: 64
    lore:
    - '&f'
    - 'display-lore-category-name-kitchen'
    resource:
      generate: false
      material: PAPER
      #textures:
      model_path: item/mixingbowlitem
  potitem:
    display_name: display-name-potitem
    durability:
      max_custom_durability: 64
    lore:
    - '&f'
    - 'display-lore-category-name-kitchen'
    resource:
      generate: false
      material: PAPER
      #textures:
      model_path: item/potitem
  rolleritem:
    display_name: display-name-rolleritem
    durability:
      max_custom_durability: 64
    lore:
    - '&f'
    - 'display-lore-category-name-kitchen'
    resource:
      generate: false
      material: PAPER
      #textures:
      model_path: item/rolleritem
  saucepanitem:
    display_name: display-name-saucepanitem
    durability:
      max_custom_durability: 64
    lore:
    - '&f'
    - 'display-lore-category-name-kitchen'
    resource:
      generate: false
      material: PAPER
      #textures:
      model_path: item/saucepanitem
  skilletitem:
    display_name: display-name-skilletitem
    durability:
      max_custom_durability: 64
    lore:
    - '&f'
    - 'display-lore-category-name-kitchen'
    resource:
      generate: false
      material: PAPER
      #textures:
      model_path: item/skilletitem
