info:
  namespace: pamhc2foodcore

categories:
  pamhc2foodcore:
    enabled: true
    name: Utencilios de cocina
    icon: pamhc2foodcore:potitem
    items:
    - pamhc2foodcore:bakewareitem
    - pamhc2foodcore:cuttingboarditem
    - pamhc2foodcore:grinderitem
    - pamhc2foodcore:juiceritem
    - pamhc2foodcore:mixingbowlitem
    - pamhc2foodcore:potitem
    - pamhc2foodcore:saucepanitem
    - pamhc2foodcore:rolleritem
    - pamhc2foodcore:skilletitem