info:
  namespace: pamhc2foodcore

recipes:
  cooking:
    cookedgroundbeef:
      ingredient:
        item: pamhc2foodcore:groundbeefitem
      machines:
      - FURNACE
      - SMOKER
      exp: 30
      cook_time: 1200
      result:
        amount: 1
        item: pamhc2foodcore:cookedgroundbeefitem

    cookedgroundchicken:
      ingredient:
        item: pamhc2foodcore:groundchickenitem
      machines:
      - FURNACE
      - SMOKER
      exp: 30
      cook_time: 1200
      result:
        amount: 1
        item: pamhc2foodcore:cookedgroundchickenitem

    cookedgroundfish:
      ingredient:
        item: pamhc2foodcore:groundfishitem
      machines:
      - FURNACE
      - SMOKER
      exp: 30
      cook_time: 1200
      result:
        amount: 1
        item: pamhc2foodcore:cookedgroundfishitem

    cookedgroundmutton:
      ingredient:
        item: pamhc2foodcore:groundmuttonitem
      machines:
      - FURNACE
      - SMOKER
      exp: 30
      cook_time: 1200
      result:
        amount: 1
        item: pamhc2foodcore:cookedgroundmuttonitem

    cookedgroundpork:
      ingredient:
        item: pamhc2foodcore:groundporkitem
      machines:
      - FURNACE
      - SMOKER
      exp: 30
      cook_time: 1200
      result:
        amount: 1
        item: pamhc2foodcore:cookedgroundporkitem

    cookedgroundrabbit:
      ingredient:
        item: pamhc2foodcore:groundrabbititem
      machines:
      - FURNACE
      - SMOKER
      exp: 30
      cook_time: 1200
      result:
        amount: 1
        item: pamhc2foodcore:cookedgroundrabbititem

    roastedalmond:
      ingredient:
        item: pamhc2trees:almonditem
      machines:
      - FURNACE
      - SMOKER
      exp: 30
      cook_time: 1200
      result:
        amount: 1
        item: pamhc2trees:roastedalmonditem

    roastedcashew:
      ingredient:
        item: pamhc2trees:cashewitem
      machines:
      - FURNACE
      - SMOKER
      exp: 30
      cook_time: 1200
      result:
        amount: 1
        item: pamhc2trees:roastedcashewitem

    roastedchestnut:
      ingredient:
        item: pamhc2trees:chestnutitem
      machines:
      - FURNACE
      - SMOKER
      exp: 30
      cook_time: 1200
      result:
        amount: 1
        item: pamhc2trees:roastedchestnutitem

    roastedgarlic:
      ingredient:
        item: pamhc2crops:garlicitem
      machines:
      - FURNACE
      - SMOKER
      exp: 30
      cook_time: 1200
      result:
        amount: 1
        item: pamhc2crops:roastedgarlicitem

    roastedhazelnut:
      ingredient:
        item: pamhc2trees:hazelnutitem
      machines:
      - FURNACE
      - SMOKER
      exp: 30
      cook_time: 1200
      result:
        amount: 1
        item: pamhc2trees:roastedhazelnutitem

    roastedkohlrabi:
      ingredient:
        item: pamhc2crops:kohlrabiitem
      machines:
      - FURNACE
      - SMOKER
      exp: 30
      cook_time: 1200
      result:
        amount: 1
        item: pamhc2crops:roastedkohlrabiitem

    roastedleek:
      ingredient:
        item: pamhc2crops:leekitem
      machines:
      - FURNACE
      - SMOKER
      exp: 30
      cook_time: 1200
      result:
        amount: 1
        item: pamhc2crops:roastedleekitem

    roastedmushroom:
      ingredient:
        item: pamhc2crops:whitemushroomitem
      machines:
      - FURNACE
      - SMOKER
      exp: 30
      cook_time: 1200
      result:
        amount: 1
        item: pamhc2crops:roastedmushroomitem

    roastedonion:
      ingredient:
        item: pamhc2crops:onionitem
      machines:
      - FURNACE
      - SMOKER
      exp: 30
      cook_time: 1200
      result:
        amount: 1
        item: pamhc2crops:roastedonionitem

    roastedscallion:
      ingredient:
        item: pamhc2crops:scallionitem
      machines:
      - FURNACE
      - SMOKER
      exp: 30
      cook_time: 1200
      result:
        amount: 1
        item: pamhc2crops:roastedscallionitem

    roastedrhubarb:
      ingredient:
        item: pamhc2crops:rhubarbitem
      machines:
      - FURNACE
      - SMOKER
      exp: 30
      cook_time: 1200
      result:
        amount: 1
        item: pamhc2crops:roastedrhubarbitem

    roastedradish:
      ingredient:
        item: pamhc2crops:radishitem
      machines:
      - FURNACE
      - SMOKER
      exp: 30
      cook_time: 1200
      result:
        amount: 1
        item: pamhc2crops:roastedradishitem

    roastedpeanut:
      ingredient:
        item: pamhc2crops:peanutitem
      machines:
      - FURNACE
      - SMOKER
      exp: 30
      cook_time: 1200
      result:
        amount: 1
        item: pamhc2crops:roastedpeanutitem

    roastedsunflowerseeds:
      ingredient:
        item: pamhc2foodcore:sunflowerseedsitem
      machines:
      - FURNACE
      - SMOKER
      exp: 30
      cook_time: 1200
      result:
        amount: 1
        item: pamhc2foodcore:roastedsunflowerseedsitem
    
    hottea:
      ingredient:
        item: pamhc2crops:tealeafitem
      machines:
      - FURNACE
      exp: 10
      cook_time: 600
      result:
        amount: 1
        item: pamhc2crops:hotteaitem

    hotcoffee:
      ingredient:
        item: pamhc2crops:coffeebeanitem
      machines:
      - FURNACE
      exp: 10
      cook_time: 600
      result:
        amount: 1
        item: pamhc2crops:hotcoffeeitem

    hotnettletea:
      ingredient:
        item: pamhc2crops:nettlesitem
      machines:
      - FURNACE
      exp: 10
      cook_time: 600
      result:
        amount: 1
        item: pamhc2crops:hotnettleteaitem

    bakedarrowroot:
      ingredient:
        item: pamhc2crops:arrowrootitem
      machines:
      - FURNACE
      - SMOKER
      exp: 30
      cook_time: 1200
      result:
        amount: 1
        item: pamhc2crops:bakedarrowrootitem

    bakedcassava:
      ingredient:
        item: pamhc2crops:cassavaitem
      machines:
      - FURNACE
      - SMOKER
      exp: 30
      cook_time: 1200
      result:
        amount: 1
        item: pamhc2crops:bakedcassavaitem

    bakedjicama:
      ingredient:
        item: pamhc2crops:jicamaitem
      machines:
      - FURNACE
      - SMOKER
      exp: 30
      cook_time: 1200
      result:
        amount: 1
        item: pamhc2crops:bakedjicamaitem

    bakedparsnip:
      ingredient:
        item: pamhc2crops:parsnipitem
      machines:
      - FURNACE
      - SMOKER
      exp: 30
      cook_time: 1200
      result:
        amount: 1
        item: pamhc2crops:bakedparsnipitem

    bakedrutabaga:
      ingredient:
        item: pamhc2crops:rutabagaitem
      machines:
      - FURNACE
      - SMOKER
      exp: 30
      cook_time: 1200
      result:
        amount: 1
        item: pamhc2crops:bakedrutabagaitem

    bakedsunchoke:
      ingredient:
        item: pamhc2crops:sunchokeitem
      machines:
      - FURNACE
      - SMOKER
      exp: 30
      cook_time: 1200
      result:
        amount: 1
        item: pamhc2crops:bakedsunchokeitem

    bakedsweetpotato:
      ingredient:
        item: pamhc2crops:sweetpotatoitem
      machines:
      - FURNACE
      - SMOKER
      exp: 30
      cook_time: 1200
      result:
        amount: 1
        item: pamhc2crops:bakedsweetpotatoitem

    bakedtaro:
      ingredient:
        item: pamhc2crops:taroitem
      machines:
      - FURNACE
      - SMOKER
      exp: 30
      cook_time: 1200
      result:
        amount: 1
        item: pamhc2crops:bakedtaroitem

    bakedturnip:
      ingredient:
        item: pamhc2crops:turnipitem
      machines:
      - FURNACE
      - SMOKER
      exp: 30
      cook_time: 1200
      result:
        amount: 1
        item: pamhc2crops:bakedturnipitem

    bakedwaterchestnut:
      ingredient:
        item: pamhc2crops:waterchestnutitem
      machines:
      - FURNACE
      - SMOKER
      exp: 30
      cook_time: 1200
      result:
        amount: 1
        item: pamhc2crops:bakedwaterchestnutitem