#   CREDITS:
#
#   Translated by: Kissadere
#   Twitter: @Kissadere
#   E-mail: kissadere@zibuu.net
#   Website: www.zibuu.net
#
info:
    namespace: drugs
    dictionary-lang: "en"
dictionary:
    # Categories and lore
    display-category-name-drugs: 'Psychetropic Substances'
    display-lore-category-name-drugs: '&8Psychetropic substances'
    # Items
    display-name-cocaineseed: "Cocaine seed"
    display-name-cocaineleaf: "Cocaine leaf"
    display-name-cocaine: "Cocaine"
    display-name-cocainepackage: "Cocaine package"
    display-name-weedseed: "Weed seed"
    display-name-weedleaf: "Weed leaf"
    display-name-joint: "Joint"
    display-name-weedpackage: "Weed package"
    display-name-tobaccoleaf: "Tobacco leaf"
    display-name-driedtobaccoleaf: "Dried tobacco leaf"
    display-name-tobacco: "Tobacco"
    display-name-cigar: "Cigar"
    display-name-cigarette: "Cigarette"
    display-name-peyote: "Peyote"
    display-name-peyoteslice: "Peyote slice"
    display-name-magicmushroom: "Magic mushroom"
    display-name-lsaseed: "LSA seed"
    display-name-lsapowder: "LSA powder"
    display-name-lsdblotter: "LSD"
    display-name-pipewithlsa: "Pipe with LSA"
    display-name-lsakohresidue: "LSA Residues"
    display-name-cbpill: "CB pill"
    display-name-mdmapill: "MDMA pill"
    display-name-emptypipe: "Empty pipe"
    display-name-filter: "Filter"