info:
  namespace: pamhc2crops

categories:
  pamhc2crops:
    enabled: true
    name: display-category-name-crops
    icon: pamhc2crops:agaveitem
    items:
    - pamhc2crops:agaveitem
    - pamhc2crops:alfalfaitem
    - pamhc2crops:aloeitem
    - pamhc2crops:amaranthitem
    - pamhc2crops:arrowrootitem
    - pamhc2crops:artichokeitem
    - pamhc2crops:asparagusitem
    - pamhc2crops:barleyitem
    - pamhc2crops:barrelcactusitem
    - pamhc2crops:beanitem
    - pamhc2crops:bellpepperitem
    - pamhc2crops:blackberryitem
    - pamhc2crops:blueberryitem
    - pamhc2crops:bokchoyitem
    - pamhc2crops:broccoliitem
    - pamhc2crops:brusselsproutitem
    - pamhc2crops:cabbageitem
    - pamhc2crops:cactusfruititem
    - pamhc2crops:calabashitem
    - pamhc2crops:candleberryitem
    - pamhc2crops:canolaitem
    - pamhc2crops:cantaloupeitem
    - pamhc2crops:cassavaitem
    - pamhc2crops:cattailitem
    - pamhc2crops:caulifloweritem
    - pamhc2crops:celeryitem
    - pamhc2crops:chiaitem
    - pamhc2crops:chickpeaitem
    - pamhc2crops:chilipepperitem
    - pamhc2crops:cloudberryitem
    - pamhc2crops:coffeebeanitem
    - pamhc2crops:cornitem
    - pamhc2crops:cottonitem
    - pamhc2crops:cranberryitem
    - pamhc2crops:cucumberitem
    - pamhc2crops:desktop
    - pamhc2crops:eggplantitem
    - pamhc2crops:elderberryitem
    - pamhc2crops:flaxitem
    - pamhc2crops:garlicitem
    - pamhc2crops:gingeritem
    - pamhc2crops:grapeitem
    - pamhc2crops:greengrapeitem
    - pamhc2crops:guaranaitem
    - pamhc2crops:huckleberryitem
    - pamhc2crops:jicamaitem
    - pamhc2crops:juniperberryitem
    - pamhc2crops:juteitem
    - pamhc2crops:kaleitem
    - pamhc2crops:kenafitem
    - pamhc2crops:kiwiitem
    - pamhc2crops:kohlrabiitem
    - pamhc2crops:leekitem
    - pamhc2crops:lentilitem
    - pamhc2crops:lettuceitem
    - pamhc2crops:lotusitem
    - pamhc2crops:milletitem
    - pamhc2crops:mulberryitem
    - pamhc2crops:mustardseedsitem
    - pamhc2crops:nettlesitem
    - pamhc2crops:nopalesitem
    - pamhc2crops:oatsitem
    - pamhc2crops:okraitem
    - pamhc2crops:onionitem
    - pamhc2crops:papyrusitem
    - pamhc2crops:parsnipitem
    - pamhc2crops:peanutitem
    - pamhc2crops:peasitem
    - pamhc2crops:pineappleitem
    - pamhc2crops:quinoaitem
    - pamhc2crops:radishitem
    - pamhc2crops:raspberryitem
    - pamhc2crops:rhubarbitem
    - pamhc2crops:riceitem
    - pamhc2crops:roastedgarlicitem
    - pamhc2crops:roastedkohlrabiitem
    - pamhc2crops:roastedleekitem
    - pamhc2crops:roastedmushroomitem
    - pamhc2crops:roastedonionitem
    - pamhc2crops:roastedpeanutitem
    - pamhc2crops:roastedradishitem
    - pamhc2crops:roastedrhubarbitem
    - pamhc2crops:roastedscallionitem
    - pamhc2crops:rutabagaitem
    - pamhc2crops:ryeitem
    - pamhc2crops:scallionitem
    - pamhc2crops:sesameseedsitem
    - pamhc2crops:sisalitem
    - pamhc2crops:sorghumitem
    - pamhc2crops:soybeanitem
    - pamhc2crops:spiceleafitem
    - pamhc2crops:spinachitem
    - pamhc2crops:strawberryitem
    - pamhc2crops:sunchokeitem
    - pamhc2crops:sweetpotatoitem
    - pamhc2crops:taroitem
    - pamhc2crops:tealeafitem
    - pamhc2crops:tomatilloitem
    - pamhc2crops:tomatoitem
    - pamhc2crops:truffleitem
    - pamhc2crops:turnipitem
    - pamhc2crops:waterchestnutitem
    - pamhc2crops:whitemushroomitem
    - pamhc2crops:wintersquashitem
    - pamhc2crops:wolfberryitem
    - pamhc2crops:yuccaitem
    - pamhc2crops:zucchiniitem