#   CREDITS:
#
#   Translated by: Terastraz
#   Twitter: @beyre83
#   E-mail: beyre83@gmail.com
#   Website: website.com
#
info:
    namespace: zcrops
    dictionary-lang: "en"
dictionary:
    # Category & Lore
    display-category-name-crops: 'Seeds and Ingredients'
    display-lore-saturation-value-crops: '&a+1 &7Saturation'
    display-lore-food-value-crops: '&a+1 &7Meal'
    display-lore-category-name-crops: '&8Seeds and Ingredients'
    # Crops
    display-name-agaveitem: Agave
    display-name-alfalfaitem: Alfalfa
    display-name-aloeitem: Aloe
    display-name-amaranthitem: Amaranth
    display-name-arrowrootitem: Arrowroot
    display-name-artichokeitem: Artichoke
    display-name-asparagusitem: Asparagus
    display-name-barleyitem: Barley
    display-name-barrelcactusitem: Barrel Cactus
    display-name-beanitem: Bean
    display-name-bellpepperitem: Bell Pepper
    display-name-blackberryitem: Blackberry
    display-name-blueberryitem: Blueberry
    display-name-bokchoyitem: Bok Choy
    display-name-broccoliitem: Broccoli
    display-name-brusselsproutitem: Brussel Sprouts
    display-name-cabbageitem: Cabbage
    display-name-cactusfruititem: Cactus Fruit
    display-name-calabashitem: Calabash
    display-name-candleberryitem: Candleberry
    display-name-canolaitem: Canola
    display-name-cantaloupeitem: Cantaloupe
    display-name-cassavaitem: Cassava
    display-name-cattailitem: Cattail
    display-name-caulifloweritem: Cauliflower
    display-name-celeryitem: Celery
    display-name-chiaitem: Chia
    display-name-chickpeaitem: Chickpea
    display-name-chilipepperitem: Chili
    display-name-cloudberryitem: Cloudberry
    display-name-coffeebeanitem: Coffee Bean
    display-name-cornitem: Corn
    display-name-cottonitem: Cotton
    display-name-cranberryitem: Cranberry
    display-name-cucumberitem: Cucumber
    display-name-eggplantitem: Eggplant
    display-name-elderberryitem: Elderberry
    display-name-flaxitem: Flax
    display-name-garlicitem: Garlic
    display-name-gingeritem: Ginger
    display-name-grapeitem: Grapes
    display-name-greengrapeitem: Green Grapes
    display-name-guaranaitem: Guarana
    display-name-huckleberryitem: Huckleberry
    display-name-jicamaitem: Jicama
    display-name-juniperberryitem: Juniperberry
    display-name-juteitem: Jute
    display-name-kaleitem: Kale
    display-name-kenafitem: Kenaf
    display-name-kiwiitem: Kiwi
    display-name-kohlrabiitem: Kohlrabi
    display-name-leekitem: Leek
    display-name-lentilitem: Lentil
    display-name-lettuceitem: Lettuce
    display-name-lotusitem: Lotus
    display-name-milletitem: Millet
    display-name-mulberryitem: Mulberry
    display-name-mustardseedsitem: Mustard Seeds
    display-name-nettlesitem: Nettles
    display-name-nopalesitem: Nopales
    display-name-oatsitem: Oats
    display-name-okraitem: Okra
    display-name-onionitem: Onion
    display-name-papyrusitem: Papyrus
    display-name-parsnipitem: Parsnip
    display-name-peanutitem: Peanut
    display-name-peasitem: Peas
    display-name-pineappleitem: Pineapple
    display-name-quinoaitem: Quinoa
    display-name-radishitem: Radish
    display-name-raspberryitem: Raspberry
    display-name-rhubarbitem: Rhubarb
    display-name-riceitem: Rice
    display-name-rutabagaitem: Rutabaga
    display-name-ryeitem: Rye
    display-name-scallionitem: Scallion
    display-name-sesameseedsitem: Sesame Seeds
    display-name-sisalitem: Sisal
    display-name-sorghumitem: Sorghum
    display-name-soybeanitem: Soya Bean
    display-name-spiceleafitem: Spice Leaf
    display-name-spinachitem: Spinach
    display-name-strawberryitem: Strawberry
    display-name-sunchokeitem: Sunchoke
    display-name-sweetpotatoitem: Sweet Potato
    display-name-taroitem: Taro
    display-name-tealeafitem: Tea Leaf
    display-name-tomatilloitem: Tomatillo
    display-name-tomatoitem: Tomato
    display-name-truffleitem: Truffle
    display-name-turnipitem: Turnip
    display-name-waterchestnutitem: Water Chestnut
    display-name-whitemushroomitem: White Mushroom
    display-name-wintersquashitem: Butternut Squash
    display-name-wolfberryitem: Goji Berry
    display-name-yuccaitem: Yucca
    display-name-zucchiniitem: Zucchini
    # End of Crops
    # Seeds
    display-name-agaveseed: Agave Seeds
    display-name-alfalfaseed: Alfalfa Seeds
    display-name-aloeseed: Aloe Seeds
    display-name-amaranthseed: Amaranth Seeds
    display-name-arrowrootseed: Arrowroot Seeds
    display-name-artichokeseed: Artichoke Seeds
    display-name-asparagusseed: Asparagus Seeds
    display-name-barleyseed: Barley Seeds
    display-name-barrelcactusseed: Barrel Cactus Seeds
    display-name-beanseed: Bean Seeds
    display-name-bellpepperseed: Bell Pepper Seeds
    display-name-blackberryseed: Blackberry Seeds
    display-name-blueberryseed: Blueberry Seeds
    display-name-bokchoyseed: Bok Choy Seeds
    display-name-broccoliseed: Broccoli Seeds
    display-name-brusselsproutseed: Brussel Sprouts Seeds
    display-name-cabbageseed: Cabbage Seeds
    display-name-cactusfruitseed: Cactus Fruit Seeds
    display-name-calabashseed: Calabash Seeds
    display-name-candleberryseed: Candleberry Seeds
    display-name-canolaseed: Canola Seeds
    display-name-cantaloupeseed: Cantaloupe Seeds
    display-name-cassavaseed: Cassava Seeds
    display-name-cattailseed: Cattail Seeds
    display-name-cauliflowerseed: Cauliflower Seeds
    display-name-celeryseed: Celery Seeds
    display-name-chiaseed: Chia Seeds
    display-name-chickpeaseed: Chickpea Seeds
    display-name-chilipepperseed: Chili Seeds
    display-name-cloudberryseed: Cloudberry Seeds
    display-name-coffeebeanseed: Coffee Bean Seeds
    display-name-cornseed: Corn Seeds
    display-name-cottonseed: Cotton Seeds
    display-name-cranberryseed: Cranberry Seeds
    display-name-cucumberseed: Cucumber Seeds
    display-name-eggplantseed: Eggplant Seeds
    display-name-elderberryseed: Elderberry Seeds
    display-name-flaxseed: Flax Seeds
    display-name-garlicseed: Garlic Seeds
    display-name-gingerseed: Ginger Seeds
    display-name-grapeseed: Grapes Seeds
    display-name-greengrapeseed: Green Grapes Seeds
    display-name-guaranaseed: Guarana Seeds
    display-name-huckleberryseed: Huckleberry Seeds
    display-name-jicamaseed: Jicama Seeds
    display-name-juniperberryseed: Juniperberry Seeds
    display-name-juteseed: Jute Seeds
    display-name-kaleseed: Kale Seeds
    display-name-kenafseed: Kenaf Seeds
    display-name-kiwiseed: Kiwi Seeds
    display-name-kohlrabiseed: Kohlrabi Seeds
    display-name-leekseed: Leek Seeds
    display-name-lentilseed: Lentil Seeds
    display-name-lettuceseed: Lettuce Seeds
    display-name-lotusseed: Lotus Seeds
    display-name-milletseed: Millet Seeds
    display-name-mulberryseed: Mulberry Seeds
    display-name-mustardseedsseed: Mustard Seeds Seeds
    display-name-nettlesseed: Nettles Seeds
    display-name-nopalesseed: Nopales Seeds
    display-name-oatsseed: Oats Seeds
    display-name-okraseed: Okra Seeds
    display-name-onionseed: Onion Seeds
    display-name-papyrusseed: Papyrus Seeds
    display-name-parsnipseed: Parsnip Seeds
    display-name-peanutseed: Peanut Seeds
    display-name-peasseed: Peas Seeds
    display-name-pineappleseed: Pineapple Seeds
    display-name-quinoaseed: Quinoa Seeds
    display-name-radishseed: Radish Seeds
    display-name-raspberryseed: Raspberry Seeds
    display-name-rhubarbseed: Rhubarb Seeds
    display-name-riceseed: Rice Seeds
    display-name-rutabagaseed: Rutabaga Seeds
    display-name-ryeseed: Rye Seeds
    display-name-scallionseed: Scallion Seeds
    display-name-sesameseedsseed: Sesame Seeds Seeds
    display-name-sisalseed: Sisal Seeds
    display-name-sorghumseed: Sorghum Seeds
    display-name-soybeanseed: Soya Bean Seeds
    display-name-spiceleafseed: Spice Leaf Seeds
    display-name-spinachseed: Spinach Seeds
    display-name-strawberryseed: Strawberry Seeds
    display-name-sunchokeseed: Sunchoke Seeds
    display-name-sweetpotatoseed: Sweet Potato Seeds
    display-name-taroseed: Taro Seeds
    display-name-tealeafseed: Tea Leaf Seeds
    display-name-tomatilloseed: Tomatillo Seeds
    display-name-tomatoseed: Tomato Seeds
    display-name-truffleseed: Truffle Seeds
    display-name-turnipseed: Turnip Seeds
    display-name-waterchestnutseed: Water Chestnut Seeds
    display-name-whitemushroomseed: White Mushroom Seeds
    display-name-wintersquashseed: Butternut Squash Seeds
    display-name-wolfberryseed: Goji Berry Seeds
    display-name-yuccaseed: Yucca Seeds
    display-name-zucchiniseed: Zucchini Seeds
    # End of Seeds