#   CREDITS:
#
#   Translated by: Terastraz
#   Twitter: @beyre83
#   E-mail: beyre83@gmail.com
#   Website: website.com
#
info:
    namespace: zcrops
    dictionary-lang: "en"
dictionary:
    # Category & Lore
    display-category-name-crops: 'Seeds and Ingredients'
    display-lore-saturation-value-crops: '&a+1 &7Saturation'
    display-lore-food-value-crops: '&a+1 &7Meal'
    display-lore-category-name-crops: '&8Seeds and Ingredients'
    # Crops
    display-name-agaveitem: Agave
    display-name-alfalfaitem: Alfalfa
    display-name-aloeitem: Aloe
    display-name-amaranthitem: Amaranth
    display-name-arrowrootitem: Arrowroot
    display-name-artichokeitem: Artichoke
    display-name-asparagusitem: Asparagus
    display-name-barleyitem: Barley
    display-name-barrelcactusitem: Barrel Cactus
    display-name-beanitem: Bean
    display-name-bellpepperitem: Bell Pepper
    display-name-blackberryitem: Blackberry
    display-name-blueberryitem: Blueberry
    display-name-bokchoyitem: Bok Choy
    display-name-broccoliitem: Broccoli
    display-name-brusselsproutitem: Brussel Sprouts
    display-name-cabbageitem: Cabbage
    display-name-cactusfruititem: Cactus Fruit
    display-name-calabashitem: Calabash
    display-name-candleberryitem: Candleberry
    display-name-canolaitem: Canola
    display-name-cantaloupeitem: Cantaloupe
    display-name-cassavaitem: Cassava
    display-name-cattailitem: Cattail
    display-name-caulifloweritem: Cauliflower
    display-name-celeryitem: Celery
    display-name-chiaitem: Chia
    display-name-chickpeaitem: Chickpea
    display-name-chilipepperitem: Chili
    display-name-cloudberryitem: Cloudberry
    display-name-coffeebeanitem: Coffee Bean
    display-name-cornitem: Corn
    display-name-cottonitem: Cotton
    display-name-cranberryitem: Cranberry
    display-name-cucumberitem: Cucumber
    display-name-eggplantitem: Eggplant
    display-name-elderberryitem: Elderberry
    display-name-flaxitem: Flax
    display-name-garlicitem: Garlic
    display-name-gingeritem: Ginger
    display-name-grapeitem: Grapes
    display-name-greengrapeitem: Green Grapes
    display-name-guaranaitem: Guarana
    display-name-huckleberryitem: Huckleberry
    display-name-jicamaitem: Jicama
    display-name-juniperberryitem: Juniperberry
    display-name-juteitem: Jute
    display-name-kaleitem: Kale
    display-name-kenafitem: Kenaf
    display-name-kiwiitem: Kiwi
    display-name-kohlrabiitem: Kohlrabi
    display-name-leekitem: Leek
    display-name-lentilitem: Lentil
    display-name-lettuceitem: Lettuce
    display-name-lotusitem: Lotus
    display-name-milletitem: Millet
    display-name-mulberryitem: Mulberry
    display-name-mustardseedsitem: Mustard Seeds
    display-name-nettlesitem: Nettles
    display-name-nopalesitem: Nopales
    display-name-oatsitem: Oats
    display-name-okraitem: Okra
    display-name-onionitem: Onion
    display-name-papyrusitem: Papyrus
    display-name-parsnipitem: Parsnip
    display-name-peanutitem: Peanut
    display-name-peasitem: Peas
    display-name-pineappleitem: Pineapple
    display-name-quinoaitem: Quinoa
    display-name-radishitem: Radish
    display-name-raspberryitem: Raspberry
    display-name-rhubarbitem: Rhubarb
    display-name-riceitem: Rice
    display-name-rutabagaitem: Rutabaga
    display-name-ryeitem: Rye
    display-name-scallionitem: Scallion
    display-name-sesameseedsitem: Sesame Seeds
    display-name-sisalitem: Sisal
    display-name-sorghumitem: Sorghum
    display-name-soybeanitem: Soya Bean
    display-name-spiceleafitem: Spice Leaf
    display-name-spinachitem: Spinach
    display-name-strawberryitem: Strawberry
    display-name-sunchokeitem: Sunchoke
    display-name-sweetpotatoitem: Sweet Potato
    display-name-taroitem: Taro
    display-name-tealeafitem: Tea Leaf
    display-name-tomatilloitem: Tomatillo
    display-name-tomatoitem: Tomato
    display-name-truffleitem: Truffle
    display-name-turnipitem: Turnip
    display-name-waterchestnutitem: Water Chestnut
    display-name-whitemushroomitem: White Mushroom
    display-name-wintersquashitem: Butternut Squash
    display-name-wolfberryitem: Goji Berry
    display-name-yuccaitem: Yucca
    display-name-zucchiniitem: Zucchini
    # End of Crops