#   CRÉDITOS:
#
#   Traducido por: Kissadere
#   Twitter: @Kissadere
#   E-mail: kissadere@zibuu.net
#   Website: https://studio.zibuu.net/
#
info:
    namespace: zcrops
    dictionary-lang: "es"
dictionary:
    # Category & Lore
    display-category-name-crops: 'Semillas e Ingredientes'
    display-lore-saturation-value-crops: '&a+1 &7Saturacion'
    display-lore-food-value-crops: '&a+1 &7Comida'
    display-lore-category-name-crops: '&8Semillas e Ingredientes'
    # Crops
    display-name-agaveitem: Agave
    display-name-alfalfaitem: Alfalfa
    display-name-aloeitem: Aloe
    display-name-amaranthitem: Amaranto
    display-name-arrowrootitem: Arrurruz
    display-name-artichokeitem: Alcachofa
    display-name-asparagusitem: Esparrago
    display-name-barleyitem: Cebada
    display-name-barrelcactusitem: Cáctus de barril
    display-name-beanitem: Frijol
    display-name-bellpepperitem: Pimiento
    display-name-blackberryitem: Mora
    display-name-blueberryitem: Arándano
    display-name-bokchoyitem: Col China
    display-name-broccoliitem: Brócoli
    display-name-brusselsproutitem: Coles de brusela
    display-name-cabbageitem: Col
    display-name-cactusfruititem: Tuna
    display-name-calabashitem: Calabaza
    display-name-candleberryitem: Candleberry
    display-name-canolaitem: Canola
    display-name-cantaloupeitem: Melón
    display-name-cassavaitem: Mandioca
    display-name-cattailitem: Espadaña
    display-name-caulifloweritem: Coliflor
    display-name-celeryitem: Apio
    display-name-chiaitem: Chia
    display-name-chickpeaitem: Garbanzo
    display-name-chilipepperitem: Chile
    display-name-cloudberryitem: Zarzamora
    display-name-coffeebeanitem: Grano de café
    display-name-cornitem: Maiz
    display-name-cottonitem: Algodón
    display-name-cranberryitem: Arándano
    display-name-cucumberitem: Pepino
    display-name-eggplantitem: Berenjena
    display-name-elderberryitem: Saúco
    display-name-flaxitem: Linaza
    display-name-garlicitem: Ajo
    display-name-gingeritem: Jengibre
    display-name-grapeitem: Uvas
    display-name-greengrapeitem: Uvas verdes
    display-name-guaranaitem: Guaraná
    display-name-huckleberryitem: Arándano
    display-name-jicamaitem: Jicama
    display-name-juniperberryitem: Baya de enebro
    display-name-juteitem: Jute
    display-name-kaleitem: Col rizada
    display-name-kenafitem: Kenaf
    display-name-kiwiitem: Kiwi
    display-name-kohlrabiitem: Colinabo
    display-name-leekitem: Puerro
    display-name-lentilitem: Lenteja
    display-name-lettuceitem: Lechuga
    display-name-lotusitem: Loto
    display-name-milletitem: Mijo
    display-name-mulberryitem: Mora
    display-name-mustardseedsitem: Semillas de mostaza
    display-name-nettlesitem: Ortiga
    display-name-nopalesitem: Nopales
    display-name-oatsitem: Avena
    display-name-okraitem: Okra
    display-name-onionitem: Cebolla
    display-name-papyrusitem: Papiro
    display-name-parsnipitem: Chirivia
    display-name-peanutitem: Cacahuate
    display-name-peasitem: Chicharo
    display-name-pineappleitem: Piña
    display-name-quinoaitem: Quinoa
    display-name-radishitem: Rábano
    display-name-raspberryitem: Frambuesa
    display-name-rhubarbitem: Ruibardo
    display-name-riceitem: Arroz
    display-name-rutabagaitem: Nabo sueco
    display-name-ryeitem: Centeno
    display-name-scallionitem: Cebollin
    display-name-sesameseedsitem: Semillas de sésamo
    display-name-sisalitem: Sisal
    display-name-sorghumitem: Sorgo
    display-name-soybeanitem: Soja
    display-name-spiceleafitem: Especias
    display-name-spinachitem: Espinaca
    display-name-strawberryitem: Fresa
    display-name-sunchokeitem: Alcachofa
    display-name-sweetpotatoitem: Camote
    display-name-taroitem: Taro
    display-name-tealeafitem: Hoja de té
    display-name-tomatilloitem: Tomate verde
    display-name-tomatoitem: Tomate
    display-name-truffleitem: Trufa
    display-name-turnipitem: Nabo
    display-name-waterchestnutitem: Castaña
    display-name-whitemushroomitem: Seta blanca
    display-name-wintersquashitem: Calabaza
    display-name-wolfberryitem: Baya de Goji
    display-name-yuccaitem: Yuca
    display-name-zucchiniitem: Zucchini
    # End of Crops