info:
  namespace: zcrops

categories:
  zcrops:
    enabled: true
    name: display-category-name-crops
    icon: zcrops:agaveitem
    items:
    - zcrops:agaveitem
    - zcrops:alfalfaitem
    - zcrops:aloeitem
    - zcrops:amaranthitem
    - zcrops:arrowrootitem
    - zcrops:artichokeitem
    - zcrops:asparagusitem
    - zcrops:barleyitem
    - zcrops:barrelcactusitem
    - zcrops:beanitem
    - zcrops:bellpepperitem
    - zcrops:blackberryitem
    - zcrops:blueberryitem
    - zcrops:bokchoyitem
    - zcrops:broccoliitem
    - zcrops:brusselsproutitem
    - zcrops:cabbageitem
    - zcrops:cactusfruititem
    - zcrops:calabashitem
    - zcrops:candleberryitem
    - zcrops:canolaitem
    - zcrops:cantaloupeitem
    - zcrops:cassavaitem
    - zcrops:cattailitem
    - zcrops:caulifloweritem
    - zcrops:celeryitem
    - zcrops:chiaitem
    - zcrops:chickpeaitem
    - zcrops:chilipepperitem
    - zcrops:cloudberryitem
    - zcrops:coffeebeanitem
    - zcrops:cornitem
    - zcrops:cottonitem
    - zcrops:cranberryitem
    - zcrops:cucumberitem
    - zcrops:desktop
    - zcrops:eggplantitem
    - zcrops:elderberryitem
    - zcrops:flaxitem
    - zcrops:garlicitem
    - zcrops:gingeritem
    - zcrops:grapeitem
    - zcrops:greengrapeitem
    - zcrops:guaranaitem
    - zcrops:huckleberryitem
    - zcrops:jicamaitem
    - zcrops:juniperberryitem
    - zcrops:juteitem
    - zcrops:kaleitem
    - zcrops:kenafitem
    - zcrops:kiwiitem
    - zcrops:kohlrabiitem
    - zcrops:leekitem
    - zcrops:lentilitem
    - zcrops:lettuceitem
    - zcrops:lotusitem
    - zcrops:milletitem
    - zcrops:mulberryitem
    - zcrops:mustardseedsitem
    - zcrops:nettlesitem
    - zcrops:nopalesitem
    - zcrops:oatsitem
    - zcrops:okraitem
    - zcrops:onionitem
    - zcrops:papyrusitem
    - zcrops:parsnipitem
    - zcrops:peanutitem
    - zcrops:peasitem
    - zcrops:pineappleitem
    - zcrops:quinoaitem
    - zcrops:radishitem
    - zcrops:raspberryitem
    - zcrops:rhubarbitem
    - zcrops:riceitem
    - zcrops:roastedgarlicitem
    - zcrops:roastedkohlrabiitem
    - zcrops:roastedleekitem
    - zcrops:roastedmushroomitem
    - zcrops:roastedonionitem
    - zcrops:roastedpeanutitem
    - zcrops:roastedradishitem
    - zcrops:roastedrhubarbitem
    - zcrops:roastedscallionitem
    - zcrops:rutabagaitem
    - zcrops:ryeitem
    - zcrops:scallionitem
    - zcrops:sesameseedsitem
    - zcrops:sisalitem
    - zcrops:sorghumitem
    - zcrops:soybeanitem
    - zcrops:spiceleafitem
    - zcrops:spinachitem
    - zcrops:strawberryitem
    - zcrops:sunchokeitem
    - zcrops:sweetpotatoitem
    - zcrops:taroitem
    - zcrops:tealeafitem
    - zcrops:tomatilloitem
    - zcrops:tomatoitem
    - zcrops:truffleitem
    - zcrops:turnipitem
    - zcrops:waterchestnutitem
    - zcrops:whitemushroomitem
    - zcrops:wintersquashitem
    - zcrops:wolfberryitem
    - zcrops:yuccaitem
    - zcrops:zucchiniitem
    # Seeds
    - zcrops:agaveseeditem
    - zcrops:alfalfaseeditem
    - zcrops:aloeseeditem
    - zcrops:amaranthseeditem
    - zcrops:arrowrootseeditem
    - zcrops:artichokeseeditem
    - zcrops:asparagusseeditem
    - zcrops:barleyseeditem
    - zcrops:barrelcactusseeditem
    - zcrops:beanseeditem
    - zcrops:bellpepperseeditem
    - zcrops:blackberryseeditem
    - zcrops:blueberryseeditem
    - zcrops:bokchoyseeditem
    - zcrops:broccoliseeditem
    - zcrops:brusselsproutseeditem
    - zcrops:cabbageseeditem
    - zcrops:cactusfruitseeditem
    - zcrops:calabashseeditem
    - zcrops:candleberryseeditem
    - zcrops:canolaseeditem
    - zcrops:cantaloupeseeditem
    - zcrops:cassavaseeditem
    - zcrops:cattailseeditem
    - zcrops:cauliflowerseeditem
    - zcrops:celeryseeditem
    - zcrops:chiaseeditem
    - zcrops:chickpeaseeditem
    - zcrops:chilipepperseeditem
    - zcrops:cloudberryseeditem
    - zcrops:coffeebeanseeditem
    - zcrops:cornseeditem
    - zcrops:cottonseeditem
    - zcrops:cranberryseeditem
    - zcrops:cucumberseeditem
    - zcrops:desktop
    - zcrops:eggplantseeditem
    - zcrops:elderberryseeditem
    - zcrops:flaxseeditem
    - zcrops:garlicseeditem
    - zcrops:gingerseeditem
    - zcrops:grapeseeditem
    - zcrops:greengrapeseeditem
    - zcrops:guaranaseeditem
    - zcrops:huckleberryseeditem
    - zcrops:jicamaseeditem
    - zcrops:juniperberryseeditem
    - zcrops:juteseeditem
    - zcrops:kaleseeditem
    - zcrops:kenafseeditem
    - zcrops:kiwiseeditem
    - zcrops:kohlrabiseeditem
    - zcrops:leekseeditem
    - zcrops:lentilseeditem
    - zcrops:lettuceseeditem
    - zcrops:lotusseeditem
    - zcrops:milletseeditem
    - zcrops:mulberryseeditem
    - zcrops:mustardseedsseeditem
    - zcrops:nettlesseeditem
    - zcrops:nopalesseeditem
    - zcrops:oatsseeditem
    - zcrops:okraseeditem
    - zcrops:onionseeditem
    - zcrops:papyrusseeditem
    - zcrops:parsnipseeditem
    - zcrops:peanutseeditem
    - zcrops:peasseeditem
    - zcrops:pineappleseeditem
    - zcrops:quinoaseeditem
    - zcrops:radishseeditem
    - zcrops:raspberryseeditem
    - zcrops:rhubarbseeditem
    - zcrops:riceseeditem
    - zcrops:roastedgarlicseeditem
    - zcrops:roastedkohlrabiseeditem
    - zcrops:roastedleekseeditem
    - zcrops:roastedmushroomseeditem
    - zcrops:roastedonionseeditem
    - zcrops:roastedpeanutseeditem
    - zcrops:roastedradishseeditem
    - zcrops:roastedrhubarbseeditem
    - zcrops:roastedscallionseeditem
    - zcrops:rutabagaseeditem
    - zcrops:ryeseeditem
    - zcrops:scallionseeditem
    - zcrops:sesameseedsseeditem
    - zcrops:sisalseeditem
    - zcrops:sorghumseeditem
    - zcrops:soybeanseeditem
    - zcrops:spiceleafseeditem
    - zcrops:spinachseeditem
    - zcrops:strawberryseeditem
    - zcrops:sunchokeseeditem
    - zcrops:sweetpotatoseeditem
    - zcrops:taroseeditem
    - zcrops:tealeafseeditem
    - zcrops:tomatilloseeditem
    - zcrops:tomatoseeditem
    - zcrops:truffleseeditem
    - zcrops:turnipseeditem
    - zcrops:waterchestnutseeditem
    - zcrops:whseeditemushroomseeditem
    - zcrops:wintersquashseeditem
    - zcrops:wolfberryseeditem
    - zcrops:yuccaseeditem
    - zcrops:zucchiniseeditem