info:
  namespace: zcrops

categories:
  zcrops:
    enabled: true
    name: display-category-name-crops
    icon: zcrops:agaveitem
    items:
    - zcrops:agaveitem
    - zcrops:alfalfaitem
    - zcrops:aloeitem
    - zcrops:amaranthitem
    - zcrops:arrowrootitem
    - zcrops:artichokeitem
    - zcrops:asparagusitem
    - zcrops:barleyitem
    - zcrops:barrelcactusitem
    - zcrops:beanitem
    - zcrops:bellpepperitem
    - zcrops:blackberryitem
    - zcrops:blueberryitem
    - zcrops:bokchoyitem
    - zcrops:broccoliitem
    - zcrops:brusselsproutitem
    - zcrops:cabbageitem
    - zcrops:cactusfruititem
    - zcrops:calabashitem
    - zcrops:candleberryitem
    - zcrops:canolaitem
    - zcrops:cantaloupeitem
    - zcrops:cassavaitem
    - zcrops:cattailitem
    - zcrops:caulifloweritem
    - zcrops:celeryitem
    - zcrops:chiaitem
    - zcrops:chickpeaitem
    - zcrops:chilipepperitem
    - zcrops:cloudberryitem
    - zcrops:coffeebeanitem
    - zcrops:cornitem
    - zcrops:cottonitem
    - zcrops:cranberryitem
    - zcrops:cucumberitem
    - zcrops:desktop
    - zcrops:eggplantitem
    - zcrops:elderberryitem
    - zcrops:flaxitem
    - zcrops:garlicitem
    - zcrops:gingeritem
    - zcrops:grapeitem
    - zcrops:greengrapeitem
    - zcrops:guaranaitem
    - zcrops:huckleberryitem
    - zcrops:jicamaitem
    - zcrops:juniperberryitem
    - zcrops:juteitem
    - zcrops:kaleitem
    - zcrops:kenafitem
    - zcrops:kiwiitem
    - zcrops:kohlrabiitem
    - zcrops:leekitem
    - zcrops:lentilitem
    - zcrops:lettuceitem
    - zcrops:lotusitem
    - zcrops:milletitem
    - zcrops:mulberryitem
    - zcrops:mustardseedsitem
    - zcrops:nettlesitem
    - zcrops:nopalesitem
    - zcrops:oatsitem
    - zcrops:okraitem
    - zcrops:onionitem
    - zcrops:papyrusitem
    - zcrops:parsnipitem
    - zcrops:peanutitem
    - zcrops:peasitem
    - zcrops:pineappleitem
    - zcrops:quinoaitem
    - zcrops:radishitem
    - zcrops:raspberryitem
    - zcrops:rhubarbitem
    - zcrops:riceitem
    - zcrops:roastedgarlicitem
    - zcrops:roastedkohlrabiitem
    - zcrops:roastedleekitem
    - zcrops:roastedmushroomitem
    - zcrops:roastedonionitem
    - zcrops:roastedpeanutitem
    - zcrops:roastedradishitem
    - zcrops:roastedrhubarbitem
    - zcrops:roastedscallionitem
    - zcrops:rutabagaitem
    - zcrops:ryeitem
    - zcrops:scallionitem
    - zcrops:sesameseedsitem
    - zcrops:sisalitem
    - zcrops:sorghumitem
    - zcrops:soybeanitem
    - zcrops:spiceleafitem
    - zcrops:spinachitem
    - zcrops:strawberryitem
    - zcrops:sunchokeitem
    - zcrops:sweetpotatoitem
    - zcrops:taroitem
    - zcrops:tealeafitem
    - zcrops:tomatilloitem
    - zcrops:tomatoitem
    - zcrops:truffleitem
    - zcrops:turnipitem
    - zcrops:waterchestnutitem
    - zcrops:whitemushroomitem
    - zcrops:wintersquashitem
    - zcrops:wolfberryitem
    - zcrops:yuccaitem
    - zcrops:zucchiniitem