info:
  namespace: zfood

categories:
  zfood:
    enabled: true
    name: display-category-name-food
    icon: zfood:baconandeggsitem
    items:
    - zfood:applejellyitem
    - zfood:applejellytoastitem
    - zfood:applejuiceitem
    - zfood:applepieitem
    - zfood:applesauceitem
    - zfood:applesmoothieitem
    - zfood:appleyogurtitem
    - zfood:baconandeggsitem
    - zfood:baconcheeseburgeritem
    - zfood:bakedvegetablemedlyitem
    - zfood:basiccheeseburgeritem
    - zfood:basicchickensandwichitem
    - zfood:basicfishsandwichitem
    - zfood:basichamburgeritem
    - zfood:batteritem
    - zfood:beefjerkyitem
    - zfood:boiledeggitem
    - zfood:butteredbakedpotatoitem
    - zfood:butteritem
    - zfood:caramelappleitem
    - zfood:caramelcupcakeitem
    - zfood:caramelicecreamitem
    - zfood:caramelitem
    - zfood:caramelmuffinitem
    - zfood:caramelyogurtitem
    - zfood:carrotbreaditem
    - zfood:carrotcakeitem
    - zfood:carrotcupcakeitem
    - zfood:carrotmuffinitem
    - zfood:carrotsoupitem
    - zfood:cheesecakeitem
    - zfood:cheeseitem
    - zfood:chickendinneritem
    - zfood:chickenjerkyitem
    - zfood:chickennuggetitem
    - zfood:chickenpotpieitem
    - zfood:chocolatebaconitem
    - zfood:chocolatebaritem
    - zfood:chocolatecakeitem
    - zfood:chocolatecaramelfudgeitem
    - zfood:chocolatecupcakeitem
    - zfood:chocolatedonutitem
    - zfood:chocolateicecreamitem
    - zfood:chocolatemilkitem
    - zfood:chocolatemilkshakeitem
    - zfood:chocolatemuffinitem
    - zfood:chocolatepuddingitem
    - zfood:chocolaterollitem
    - zfood:chocolateyogurtitem
    - zfood:cocoapowderitem
    - zfood:cookedgroundbeefitem
    - zfood:cookedgroundchickenitem
    - zfood:cookedgroundfishitem
    - zfood:cookedgroundmuttonitem
    - zfood:cookedgroundporkitem
    - zfood:cookedgroundrabbititem
    - zfood:cookiesandmilkitem
    - zfood:cookingoilitem
    - zfood:cottoncandyitem
    - zfood:crackeritem
    - zfood:creamitem
    - zfood:donutitem
    - zfood:doughitem
    - zfood:fishandchipsitem
    - zfood:fishjerkyitem
    - zfood:fishsticksitem
    - zfood:flouritem
    - zfood:freshmilkitem
    - zfood:freshwateritem
    - zfood:friedchickenitem
    - zfood:friedeggitem
    - zfood:friesitem
    - zfood:fruitcrumbleitem
    - zfood:fruitpunchitem
    - zfood:fruitsaladitem
    - zfood:glazedcarrotsitem
    - zfood:glowberryjellyitem
    - zfood:glowberryjellytoastitem
    - zfood:glowberryjuiceitem
    - zfood:glowberrypieitem
    - zfood:glowberrysmoothieitem
    - zfood:glowberryyogurtitem
    - zfood:grilledcheeseitem
    - zfood:groundbeefitem
    - zfood:groundchickenitem
    - zfood:groundfishitem
    - zfood:groundmuttonitem
    - zfood:groundporkitem
    - zfood:groundrabbititem
    - zfood:gummybearsitem
    - zfood:hotchocolateitem
    - zfood:hotdogitem
    - zfood:icecreamitem
    - zfood:jellybeansitem
    - zfood:jellydonutitem
    - zfood:macncheeseitem
    - zfood:marshmellowchicksitem
    - zfood:marshmellowsitem
    - zfood:mashedpotatoesitem
    - zfood:mayonaiseitem
    - zfood:meatloafitem
    - zfood:melonjellyitem
    - zfood:melonjellytoastitem
    - zfood:melonjuiceitem
    - zfood:melonsmoothieitem
    - zfood:melonyogurtitem
    - zfood:muttonjerkyitem
    - zfood:noodlesitem
    - zfood:noodlesoupitem
    - zfood:p8juiceitem
    - zfood:pastaitem
    - zfood:pickledbeetsitem
    - zfood:porkjerkyitem
    - zfood:potatochipsitem
    - zfood:potatosaladitem
    - zfood:potatosoupitem
    - zfood:potroastitem
    - zfood:pumpkinbreaditem
    - zfood:pumpkincheesecakeitem
    - zfood:pumpkincupcakeitem
    - zfood:pumpkinmuffinitem
    - zfood:pumpkinsoupitem
    - zfood:pumpkinyogurtitem
    - zfood:rabbitjerkyitem
    - zfood:roastedsunflowerseedsitem
    - zfood:saltitem
    - zfood:scrambledeggitem
    - zfood:smoresitem
    - zfood:softpretzelitem
    - zfood:stewitem
    - zfood:stockitem
    - zfood:sunflowerseedsitem
    - zfood:sweetberryjellyitem
    - zfood:sweetberryjellytoastitem
    - zfood:sweetberryjuiceitem
    - zfood:sweetberrypieitem
    - zfood:sweetberrysmoothieitem
    - zfood:sweetberryyogurtitem
    - zfood:toastitem
    - zfood:trailmixitem
    - zfood:vinegaritem
    - zfood:yogurtitem
    - zfood:hotcoffeeitem
    - zfood:hotnettleteaitem
    - zfood:hotteaitem
    - zfood:roastedacornitem
    - zfood:roastedalmonditem
    - zfood:roastedcashewitem
    - zfood:roastedchestnutitem
    - zfood:roastedhazelnutitem
    - zfood:roastedpecanitem
    - zfood:roastedpinenutitem
    - zfood:roastedpistachioitem
    - zfood:roastedwalnutitem
    - zfood:bakedarrowrootitem
    - zfood:bakedcassavaitem
    - zfood:bakedjicamaitem
    - zfood:bakedparsnipitem
    - zfood:bakedrutabagaitem
    - zfood:bakedsunchokeitem
    - zfood:bakedsweetpotatoitem
    - zfood:bakedtaroitem
    - zfood:bakedturnipitem
    - zfood:bakedwaterchestnutitem