info:
  namespace: drugs

categories:
  zibuudrugs:
    permission: ia.seecategory.zibuudrugs
    enabled: true
    name: display-category-name-drugs
    icon: drugs:weedleaf
    items:
    - drugs:cocaineseed
    - drugs:cocaineleaf
    - drugs:cocaine
    - drugs:cocainepackage
    - drugs:weedseed
    - drugs:weedleaf
    - drugs:joint
    - drugs:weedpackage
    - drugs:tobaccoleaf
    - drugs:driedtobaccoleaf
    - drugs:tobacco
    - drugs:cigar
    - drugs:cigarette
    - drugs:peyote
    - drugs:peyoteslice
    - drugs:magicmushroom
    - drugs:lsaseed
    - drugs:lsapowder
    - drugs:pipewithlsa
    - drugs:lsakohresidue
    - drugs:lsdblotter
    - drugs:cbpill
    - drugs:mdmapill
    - drugs:emptypipe
    - drugs:filter