info:
  namespace: drugs

loots:
  blocks:

# Nether
    crimson_roots:
      type: CRIMSON_ROOTS
      items:
        cocaineseed:
          biomes:
          - CRIMSON_FOREST
          chance: 0.1
          ignore_fortune: true
          item: drugs:cocaineseed
          max_amount: 1
          min_amount: 1
    warped_roots:
      type: WARPED_ROOTS
      items:
        weedseed:
          biomes:
          - WARPED_FOREST
          chance: 0.1
          ignore_fortune: true
          item: drugs:weedseed
          max_amount: 1
          min_amount: 1

# Overworld
    grass:
      type: GRASS
      items:
        magicmushroom:
          chance: 5.0
          ignore_fortune: true
          item: drugs:magicmushroom
          max_amount: 1
          min_amount: 1
        lsaseed:
          chance: 0.1
          ignore_fortune: true
          item: drugs:lsaseed
          max_amount: 1
          min_amount: 1
    tallgrass:
      type: TALL_GRASS
      items:
        magicmushroom:
          chance: 5.0
          ignore_fortune: true
          item: drugs:magicmushroom
          max_amount: 1
          min_amount: 1
        lsaseed:
          chance: 0.1
          ignore_fortune: true
          item: drugs:lsaseed
          max_amount: 1
          min_amount: 1
    jungle_leaves:
      type: JUNGLE_LEAVES
      items:
        tobacco:
          biomes:
          - JUNGLE
          chance: 50.0
          ignore_fortune: true
          item: drugs:tobaccoleaf
          max_amount: 1
          min_amount: 1

# The End
    chorus_plant:
      type: CHORUS_PLANT
      items:
        peyote:
          chance: 0.1
          ignore_fortune: true
          item: drugs:peyote
          max_amount: 1
          min_amount: 1
