info:
  namespace: ztrees

categories:
  ztrees:
    enabled: true
    name: display-category-name-trees
    icon: ztrees:bananaitem
    items:
    - ztrees:acornitem
    - ztrees:almonditem
    - ztrees:apricotitem
    - ztrees:avocadoitem
    - ztrees:bananaitem
    - ztrees:breadfruititem
    - ztrees:candlenutitem
    - ztrees:cashewitem
    - ztrees:cherryitem
    - ztrees:chestnutitem
    - ztrees:cinnamonitem
    - ztrees:coconutitem
    - ztrees:dateitem
    - ztrees:dragonfruititem
    - ztrees:durianitem
    - ztrees:figitem
    - ztrees:gooseberryitem
    - ztrees:grapefruititem
    - ztrees:guavaitem
    - ztrees:hazelnutitem
    - ztrees:jackfruititem
    - ztrees:lemonitem
    - ztrees:limeitem
    - ztrees:lycheeitem
    - ztrees:mangoitem
    - ztrees:maplesyrupitem
    - ztrees:nutmegitem
    - ztrees:oliveitem
    - ztrees:orangeitem
    - ztrees:papayaitem
    - ztrees:passionfruititem
    - ztrees:pawpawitem
    - ztrees:peachitem
    - ztrees:pearitem
    - ztrees:pecanitem
    - ztrees:peppercornitem
    - ztrees:persimmonitem
    - ztrees:pinenutitem
    - ztrees:pistachioitem
    - ztrees:plumitem
    - ztrees:pomegranateitem
    - ztrees:rambutanitem
    - ztrees:soursopitem
    - ztrees:starfruititem
    - ztrees:tamarinditem
    - ztrees:vanillabeanitem
    - ztrees:walnutitem
    # Saplings
    - ztrees:almondtreesapling
    - ztrees:apricottreesapling
    - ztrees:avocadotreesapling
    - ztrees:bananatreesapling
    - ztrees:breadfruittreesapling
    - ztrees:candlenuttreesapling
    - ztrees:cashewtreesapling
    - ztrees:cherrytreesapling
    - ztrees:chestnuttreesapling
    - ztrees:cinnamontreesapling
    - ztrees:coconuttreesapling
    - ztrees:datetreesapling
    - ztrees:dragonfruittreesapling
    - ztrees:duriantreesapling
    - ztrees:figtreesapling
    - ztrees:gooseberrytreesapling
    - ztrees:grapefruittreesapling
    - ztrees:guavatreesapling
    - ztrees:hazelnuttreesapling
    - ztrees:jackfruittreesapling
    - ztrees:lemontreesapling
    - ztrees:limetreesapling
    - ztrees:lycheetreesapling
    - ztrees:mangotreesapling
    - ztrees:maplesyruptreesapling
    - ztrees:nutmegtreesapling
    - ztrees:olivetreesapling
    - ztrees:orangetreesapling
    - ztrees:papayatreesapling
    - ztrees:passionfruittreesapling
    - ztrees:pawpawtreesapling
    - ztrees:peachtreesapling
    - ztrees:peartreesapling
    - ztrees:pecantreesapling
    - ztrees:peppercorntreesapling
    - ztrees:persimmontreesapling
    - ztrees:pinenuttreesapling
    - ztrees:pistachiotreesapling
    - ztrees:plumtreesapling
    - ztrees:pomegranatetreesapling
    - ztrees:rambutantreesapling
    - ztrees:soursoptreesapling
    - ztrees:starfruittreesapling
    - ztrees:tamarindtreesapling
    - ztrees:vanillabeantreesapling
    - ztrees:walnuttreesapling