info:
  namespace: pamhc2trees

trees_populators:
  almondtree:
    worlds:
    - world
    bottom_blocks:
    - DIRT
    - GRASS_BLOCK
    - PODZOL
    chance: 0.0
    max_height: 100
    min_height: 50
    amount: 3
    iterations: 2
    tree_type: TREE
    leaves: pamhc2trees:almondtreeleaves
    log: pamhc2trees:mainlog
    biomes:
    - PLAINS
    - SUNFLOWER_PLAINS
    - MOUNTAINS
  appletree:
    worlds:
    - world
    bottom_blocks:
    - DIRT
    - GRASS_BLOCK
    - PODZOL
    chance: 0.0
    max_height: 100
    min_height: 50
    amount: 3
    iterations: 2
    tree_type: TREE
    leaves: pamhc2trees:appletreeleaves
    log: pamhc2trees:mainlog
    biomes:
    - PLAINS
    - SUNFLOWER_PLAINS
    - MOUNTAINS
  apricottree:
    worlds:
    - world
    bottom_blocks:
    - DIRT
    - GRASS_BLOCK
    - PODZOL
    chance: 0.0
    max_height: 100
    min_height: 50
    amount: 3
    iterations: 2
    tree_type: TREE
    leaves: pamhc2trees:apricottreeleaves
    log: pamhc2trees:mainlog
    biomes:
    - PLAINS
    - SUNFLOWER_PLAINS
    - MOUNTAINS
  avocadotree:
    worlds:
    - world
    bottom_blocks:
    - DIRT
    - GRASS_BLOCK
    - PODZOL
    chance: 0.0
    max_height: 100
    min_height: 50
    amount: 3
    iterations: 2
    tree_type: TREE
    leaves: pamhc2trees:avocadotreeleaves
    log: pamhc2trees:mainlog
    biomes:
    - PLAINS
    - SUNFLOWER_PLAINS
    - MOUNTAINS
  bananatree:
    worlds:
    - world
    bottom_blocks:
    - DIRT
    - GRASS_BLOCK
    - PODZOL
    chance: 0.0
    max_height: 100
    min_height: 50
    amount: 3
    iterations: 2
    tree_type: TREE
    leaves: pamhc2trees:bananatreeleaves
    log: pamhc2trees:mainlog
    biomes:
    - PLAINS
    - SUNFLOWER_PLAINS
    - MOUNTAINS
  breadfruittree:
    worlds:
    - world
    bottom_blocks:
    - DIRT
    - GRASS_BLOCK
    - PODZOL
    chance: 0.0
    max_height: 100
    min_height: 50
    amount: 3
    iterations: 2
    tree_type: TREE
    leaves: pamhc2trees:breadfruittreeleaves
    log: pamhc2trees:mainlog
    biomes:
    - PLAINS
    - SUNFLOWER_PLAINS
    - MOUNTAINS
  candlenuttree:
    worlds:
    - world
    bottom_blocks:
    - DIRT
    - GRASS_BLOCK
    - PODZOL
    chance: 0.0
    max_height: 100
    min_height: 50
    amount: 3
    iterations: 2
    tree_type: TREE
    leaves: pamhc2trees:candlenuttreeleaves
    log: pamhc2trees:mainlog
    biomes:
    - PLAINS
    - SUNFLOWER_PLAINS
    - MOUNTAINS
  cashewtree:
    worlds:
    - world
    bottom_blocks:
    - DIRT
    - GRASS_BLOCK
    - PODZOL
    chance: 0.0
    max_height: 100
    min_height: 50
    amount: 3
    iterations: 2
    tree_type: TREE
    leaves: pamhc2trees:cashewtreeleaves
    log: pamhc2trees:mainlog
    biomes:
    - PLAINS
    - SUNFLOWER_PLAINS
    - MOUNTAINS
  cherrytree:
    worlds:
    - world
    bottom_blocks:
    - DIRT
    - GRASS_BLOCK
    - PODZOL
    chance: 0.0
    max_height: 100
    min_height: 50
    amount: 3
    iterations: 2
    tree_type: TREE
    leaves: pamhc2trees:cherrytreeleaves
    log: pamhc2trees:mainlog
    biomes:
    - PLAINS
    - SUNFLOWER_PLAINS
    - MOUNTAINS
  datetree:
    worlds:
    - world
    bottom_blocks:
    - DIRT
    - GRASS_BLOCK
    - PODZOL
    chance: 0.0
    max_height: 100
    min_height: 50
    amount: 3
    iterations: 2
    tree_type: TREE
    leaves: pamhc2trees:datetreeleaves
    log: pamhc2trees:mainlog
    biomes:
    - PLAINS
    - SUNFLOWER_PLAINS
    - MOUNTAINS
  dragonfruittree:
    worlds:
    - world
    bottom_blocks:
    - DIRT
    - GRASS_BLOCK
    - PODZOL
    chance: 0.0
    max_height: 100
    min_height: 50
    amount: 3
    iterations: 2
    tree_type: TREE
    leaves: pamhc2trees:dragonfruittreeleaves
    log: pamhc2trees:mainlog
    biomes:
    - PLAINS
    - SUNFLOWER_PLAINS
    - MOUNTAINS
  duriantree:
    worlds:
    - world
    bottom_blocks:
    - DIRT
    - GRASS_BLOCK
    - PODZOL
    chance: 0.0
    max_height: 100
    min_height: 50
    amount: 3
    iterations: 2
    tree_type: TREE
    leaves: pamhc2trees:duriantreeleaves
    log: pamhc2trees:mainlog
    biomes:
    - PLAINS
    - SUNFLOWER_PLAINS
    - MOUNTAINS
  figtree:
    worlds:
    - world
    bottom_blocks:
    - DIRT
    - GRASS_BLOCK
    - PODZOL
    chance: 0.0
    max_height: 100
    min_height: 50
    amount: 3
    iterations: 2
    tree_type: TREE
    leaves: pamhc2trees:figtreeleaves
    log: pamhc2trees:mainlog
    biomes:
    - PLAINS
    - SUNFLOWER_PLAINS
    - MOUNTAINS
  gooseberrytree:
    worlds:
    - world
    bottom_blocks:
    - DIRT
    - GRASS_BLOCK
    - PODZOL
    chance: 0.0
    max_height: 100
    min_height: 50
    amount: 3
    iterations: 2
    tree_type: TREE
    leaves: pamhc2trees:gooseberrytreeleaves
    log: pamhc2trees:mainlog
    biomes:
    - PLAINS
    - SUNFLOWER_PLAINS
    - MOUNTAINS
  grapefruittree:
    worlds:
    - world
    bottom_blocks:
    - DIRT
    - GRASS_BLOCK
    - PODZOL
    chance: 0.0
    max_height: 100
    min_height: 50
    amount: 3
    iterations: 2
    tree_type: TREE
    leaves: pamhc2trees:grapefruittreeleaves
    log: pamhc2trees:mainlog
    biomes:
    - PLAINS
    - SUNFLOWER_PLAINS
    - MOUNTAINS
  guavatree:
    worlds:
    - world
    bottom_blocks:
    - DIRT
    - GRASS_BLOCK
    - PODZOL
    chance: 0.0
    max_height: 100
    min_height: 50
    amount: 3
    iterations: 2
    tree_type: TREE
    leaves: pamhc2trees:guavatreeleaves
    log: pamhc2trees:mainlog
    biomes:
    - PLAINS
    - SUNFLOWER_PLAINS
    - MOUNTAINS
  hazelnuttree:
    worlds:
    - world
    bottom_blocks:
    - DIRT
    - GRASS_BLOCK
    - PODZOL
    chance: 0.0
    max_height: 100
    min_height: 50
    amount: 3
    iterations: 2
    tree_type: TREE
    leaves: pamhc2trees:hazelnuttreeleaves
    log: pamhc2trees:mainlog
    biomes:
    - PLAINS
    - SUNFLOWER_PLAINS
    - MOUNTAINS
  jackfruittree:
    worlds:
    - world
    bottom_blocks:
    - DIRT
    - GRASS_BLOCK
    - PODZOL
    chance: 0.0
    max_height: 100
    min_height: 50
    amount: 3
    iterations: 2
    tree_type: TREE
    leaves: pamhc2trees:jackfruittreeleaves
    log: pamhc2trees:mainlog
    biomes:
    - PLAINS
    - SUNFLOWER_PLAINS
    - MOUNTAINS
  lemontree:
    worlds:
    - world
    bottom_blocks:
    - DIRT
    - GRASS_BLOCK
    - PODZOL
    chance: 0.0
    max_height: 100
    min_height: 50
    amount: 3
    iterations: 2
    tree_type: TREE
    leaves: pamhc2trees:lemontreeleaves
    log: pamhc2trees:mainlog
    biomes:
    - PLAINS
    - SUNFLOWER_PLAINS
    - MOUNTAINS
  limetree:
    worlds:
    - world
    bottom_blocks:
    - DIRT
    - GRASS_BLOCK
    - PODZOL
    chance: 0.0
    max_height: 100
    min_height: 50
    amount: 3
    iterations: 2
    tree_type: TREE
    leaves: pamhc2trees:limetreeleaves
    log: pamhc2trees:mainlog
    biomes:
    - PLAINS
    - SUNFLOWER_PLAINS
    - MOUNTAINS
  lycheetree:
    worlds:
    - world
    bottom_blocks:
    - DIRT
    - GRASS_BLOCK
    - PODZOL
    chance: 0.0
    max_height: 100
    min_height: 50
    amount: 3
    iterations: 2
    tree_type: TREE
    leaves: pamhc2trees:lycheetreeleaves
    log: pamhc2trees:mainlog
    biomes:
    - PLAINS
    - SUNFLOWER_PLAINS
    - MOUNTAINS
  mangotree:
    worlds:
    - world
    bottom_blocks:
    - DIRT
    - GRASS_BLOCK
    - PODZOL
    chance: 0.0
    max_height: 100
    min_height: 50
    amount: 3
    iterations: 2
    tree_type: TREE
    leaves: pamhc2trees:mangotreeleaves
    log: pamhc2trees:mainlog
    biomes:
    - PLAINS
    - SUNFLOWER_PLAINS
    - MOUNTAINS
  nutmegtree:
    worlds:
    - world
    bottom_blocks:
    - DIRT
    - GRASS_BLOCK
    - PODZOL
    chance: 0.0
    max_height: 100
    min_height: 50
    amount: 3
    iterations: 2
    tree_type: TREE
    leaves: pamhc2trees:nutmegtreeleaves
    log: pamhc2trees:mainlog
    biomes:
    - PLAINS
    - SUNFLOWER_PLAINS
    - MOUNTAINS
  olivetree:
    worlds:
    - world
    bottom_blocks:
    - DIRT
    - GRASS_BLOCK
    - PODZOL
    chance: 0.0
    max_height: 100
    min_height: 50
    amount: 3
    iterations: 2
    tree_type: TREE
    leaves: pamhc2trees:olivetreeleaves
    log: pamhc2trees:mainlog
    biomes:
    - PLAINS
    - SUNFLOWER_PLAINS
    - MOUNTAINS
  orangetree:
    worlds:
    - world
    bottom_blocks:
    - DIRT
    - GRASS_BLOCK
    - PODZOL
    chance: 0.0
    max_height: 100
    min_height: 50
    amount: 3
    iterations: 2
    tree_type: TREE
    leaves: pamhc2trees:orangetreeleaves
    log: pamhc2trees:mainlog
    biomes:
    - PLAINS
    - SUNFLOWER_PLAINS
    - MOUNTAINS
  papayatree:
    worlds:
    - world
    bottom_blocks:
    - DIRT
    - GRASS_BLOCK
    - PODZOL
    chance: 0.0
    max_height: 100
    min_height: 50
    amount: 3
    iterations: 2
    tree_type: TREE
    leaves: pamhc2trees:papayatreeleaves
    log: pamhc2trees:mainlog
    biomes:
    - PLAINS
    - SUNFLOWER_PLAINS
    - MOUNTAINS
  passionfruittree:
    worlds:
    - world
    bottom_blocks:
    - DIRT
    - GRASS_BLOCK
    - PODZOL
    chance: 0.0
    max_height: 100
    min_height: 50
    amount: 3
    iterations: 2
    tree_type: TREE
    leaves: pamhc2trees:passionfruittreeleaves
    log: pamhc2trees:mainlog
    biomes:
    - PLAINS
    - SUNFLOWER_PLAINS
    - MOUNTAINS
  pawpawtree:
    worlds:
    - world
    bottom_blocks:
    - DIRT
    - GRASS_BLOCK
    - PODZOL
    chance: 0.0
    max_height: 100
    min_height: 50
    amount: 3
    iterations: 2
    tree_type: TREE
    leaves: pamhc2trees:pawpawtreeleaves
    log: pamhc2trees:mainlog
    biomes:
    - PLAINS
    - SUNFLOWER_PLAINS
    - MOUNTAINS
  peachtree:
    worlds:
    - world
    bottom_blocks:
    - DIRT
    - GRASS_BLOCK
    - PODZOL
    chance: 0.0
    max_height: 100
    min_height: 50
    amount: 3
    iterations: 2
    tree_type: TREE
    leaves: pamhc2trees:peachtreeleaves
    log: pamhc2trees:mainlog
    biomes:
    - PLAINS
    - SUNFLOWER_PLAINS
    - MOUNTAINS
  peartree:
    worlds:
    - world
    bottom_blocks:
    - DIRT
    - GRASS_BLOCK
    - PODZOL
    chance: 0.0
    max_height: 100
    min_height: 50
    amount: 3
    iterations: 2
    tree_type: TREE
    leaves: pamhc2trees:peartreeleaves
    log: pamhc2trees:mainlog
    biomes:
    - PLAINS
    - SUNFLOWER_PLAINS
    - MOUNTAINS
  pecantree:
    worlds:
    - world
    bottom_blocks:
    - DIRT
    - GRASS_BLOCK
    - PODZOL
    chance: 0.0
    max_height: 100
    min_height: 50
    amount: 3
    iterations: 2
    tree_type: TREE
    leaves: pamhc2trees:pecantreeleaves
    log: pamhc2trees:mainlog
    biomes:
    - PLAINS
    - SUNFLOWER_PLAINS
    - MOUNTAINS
  peppercorntree:
    worlds:
    - world
    bottom_blocks:
    - DIRT
    - GRASS_BLOCK
    - PODZOL
    chance: 0.0
    max_height: 100
    min_height: 50
    amount: 3
    iterations: 2
    tree_type: TREE
    leaves: pamhc2trees:peppercorntreeleaves
    log: pamhc2trees:mainlog
    biomes:
    - PLAINS
    - SUNFLOWER_PLAINS
    - MOUNTAINS
  persimmontree:
    worlds:
    - world
    bottom_blocks:
    - DIRT
    - GRASS_BLOCK
    - PODZOL
    chance: 0.0
    max_height: 100
    min_height: 50
    amount: 3
    iterations: 2
    tree_type: TREE
    leaves: pamhc2trees:persimmontreeleaves
    log: pamhc2trees:mainlog
    biomes:
    - PLAINS
    - SUNFLOWER_PLAINS
    - MOUNTAINS
  pistachiotree:
    worlds:
    - world
    bottom_blocks:
    - DIRT
    - GRASS_BLOCK
    - PODZOL
    chance: 0.0
    max_height: 100
    min_height: 50
    amount: 3
    iterations: 2
    tree_type: TREE
    leaves: pamhc2trees:pistachiotreeleaves
    log: pamhc2trees:mainlog
    biomes:
    - PLAINS
    - SUNFLOWER_PLAINS
    - MOUNTAINS
  plumtree:
    worlds:
    - world
    bottom_blocks:
    - DIRT
    - GRASS_BLOCK
    - PODZOL
    chance: 0.0
    max_height: 100
    min_height: 50
    amount: 3
    iterations: 2
    tree_type: TREE
    leaves: pamhc2trees:plumtreeleaves
    log: pamhc2trees:mainlog
    biomes:
    - PLAINS
    - SUNFLOWER_PLAINS
    - MOUNTAINS
  pomegranatetree:
    worlds:
    - world
    bottom_blocks:
    - DIRT
    - GRASS_BLOCK
    - PODZOL
    chance: 0.0
    max_height: 100
    min_height: 50
    amount: 3
    iterations: 2
    tree_type: TREE
    leaves: pamhc2trees:pomegranatetreeleaves
    log: pamhc2trees:mainlog
    biomes:
    - PLAINS
    - SUNFLOWER_PLAINS
    - MOUNTAINS
  rambutantree:
    worlds:
    - world
    bottom_blocks:
    - DIRT
    - GRASS_BLOCK
    - PODZOL
    chance: 0.0
    max_height: 100
    min_height: 50
    amount: 3
    iterations: 2
    tree_type: TREE
    leaves: pamhc2trees:rambutantreeleaves
    log: pamhc2trees:mainlog
    biomes:
    - PLAINS
    - SUNFLOWER_PLAINS
    - MOUNTAINS
  soursoptree:
    worlds:
    - world
    bottom_blocks:
    - DIRT
    - GRASS_BLOCK
    - PODZOL
    chance: 0.0
    max_height: 100
    min_height: 50
    amount: 3
    iterations: 2
    tree_type: TREE
    leaves: pamhc2trees:soursoptreeleaves
    log: pamhc2trees:mainlog
    biomes:
    - PLAINS
    - SUNFLOWER_PLAINS
    - MOUNTAINS
  starfruittree:
    worlds:
    - world
    bottom_blocks:
    - DIRT
    - GRASS_BLOCK
    - PODZOL
    chance: 0.0
    max_height: 100
    min_height: 50
    amount: 3
    iterations: 2
    tree_type: TREE
    leaves: pamhc2trees:starfruittreeleaves
    log: pamhc2trees:mainlog
    biomes:
    - PLAINS
    - SUNFLOWER_PLAINS
    - MOUNTAINS
  tamarindtree:
    worlds:
    - world
    bottom_blocks:
    - DIRT
    - GRASS_BLOCK
    - PODZOL
    chance: 0.0
    max_height: 100
    min_height: 50
    amount: 3
    iterations: 2
    tree_type: TREE
    leaves: pamhc2trees:tamarindtreeleaves
    log: pamhc2trees:mainlog
    biomes:
    - PLAINS
    - SUNFLOWER_PLAINS
    - MOUNTAINS
  vanillabeantree:
    worlds:
    - world
    bottom_blocks:
    - DIRT
    - GRASS_BLOCK
    - PODZOL
    chance: 0.0
    max_height: 100
    min_height: 50
    amount: 3
    iterations: 2
    tree_type: TREE
    leaves: pamhc2trees:vanillabeantreeleaves
    log: pamhc2trees:mainlog
    biomes:
    - PLAINS
    - SUNFLOWER_PLAINS
    - MOUNTAINS
  walnuttree:
    worlds:
    - world
    bottom_blocks:
    - DIRT
    - GRASS_BLOCK
    - PODZOL
    chance: 0.0
    max_height: 100
    min_height: 50
    amount: 3
    iterations: 2
    tree_type: TREE
    leaves: pamhc2trees:walnuttreeleaves
    log: pamhc2trees:mainlog
    biomes:
    - PLAINS
    - SUNFLOWER_PLAINS
    - MOUNTAINS