info:
  namespace: pamhc2trees

categories:
  pamhc2trees:
    enabled: true
    name: display-category-name-trees
    icon: pamhc2trees:bananaitem
    items:
    - pamhc2trees:acornitem
    - pamhc2trees:almonditem
    - pamhc2trees:apricotitem
    - pamhc2trees:avocadoitem
    - pamhc2trees:bananaitem
    - pamhc2trees:breadfruititem
    - pamhc2trees:candlenutitem
    - pamhc2trees:cashewitem
    - pamhc2trees:cherryitem
    - pamhc2trees:chestnutitem
    - pamhc2trees:cinnamonitem
    - pamhc2trees:coconutitem
    - pamhc2trees:dateitem
    - pamhc2trees:dragonfruititem
    - pamhc2trees:durianitem
    - pamhc2trees:figitem
    - pamhc2trees:gooseberryitem
    - pamhc2trees:grapefruititem
    - pamhc2trees:guavaitem
    - pamhc2trees:hazelnutitem
    - pamhc2trees:jackfruititem
    - pamhc2trees:lemonitem
    - pamhc2trees:limeitem
    - pamhc2trees:lycheeitem
    - pamhc2trees:mangoitem
    - pamhc2trees:maplesyrupitem
    - pamhc2trees:nutmegitem
    - pamhc2trees:oliveitem
    - pamhc2trees:orangeitem
    - pamhc2trees:papayaitem
    - pamhc2trees:passionfruititem
    - pamhc2trees:pawpawitem
    - pamhc2trees:peachitem
    - pamhc2trees:pearitem
    - pamhc2trees:pecanitem
    - pamhc2trees:peppercornitem
    - pamhc2trees:persimmonitem
    - pamhc2trees:pinenutitem
    - pamhc2trees:pistachioitem
    - pamhc2trees:plumitem
    - pamhc2trees:pomegranateitem
    - pamhc2trees:rambutanitem
    - pamhc2trees:soursopitem
    - pamhc2trees:starfruititem
    - pamhc2trees:tamarinditem
    - pamhc2trees:vanillabeanitem
    - pamhc2trees:walnutitem
    # Saplings
    - pamhc2trees:almondtreesapling
    - pamhc2trees:apricottreesapling
    - pamhc2trees:avocadotreesapling
    - pamhc2trees:bananatreesapling
    - pamhc2trees:breadfruittreesapling
    - pamhc2trees:candlenuttreesapling
    - pamhc2trees:cashewtreesapling
    - pamhc2trees:cherrytreesapling
    - pamhc2trees:chestnuttreesapling
    - pamhc2trees:cinnamontreesapling
    - pamhc2trees:coconuttreesapling
    - pamhc2trees:datetreesapling
    - pamhc2trees:dragonfruittreesapling
    - pamhc2trees:duriantreesapling
    - pamhc2trees:figtreesapling
    - pamhc2trees:gooseberrytreesapling
    - pamhc2trees:grapefruittreesapling
    - pamhc2trees:guavatreesapling
    - pamhc2trees:hazelnuttreesapling
    - pamhc2trees:jackfruittreesapling
    - pamhc2trees:lemontreesapling
    - pamhc2trees:limetreesapling
    - pamhc2trees:lycheetreesapling
    - pamhc2trees:mangotreesapling
    - pamhc2trees:maplesyruptreesapling
    - pamhc2trees:nutmegtreesapling
    - pamhc2trees:olivetreesapling
    - pamhc2trees:orangetreesapling
    - pamhc2trees:papayatreesapling
    - pamhc2trees:passionfruittreesapling
    - pamhc2trees:pawpawtreesapling
    - pamhc2trees:peachtreesapling
    - pamhc2trees:peartreesapling
    - pamhc2trees:pecantreesapling
    - pamhc2trees:peppercorntreesapling
    - pamhc2trees:persimmontreesapling
    - pamhc2trees:pinenuttreesapling
    - pamhc2trees:pistachiotreesapling
    - pamhc2trees:plumtreesapling
    - pamhc2trees:pomegranatetreesapling
    - pamhc2trees:rambutantreesapling
    - pamhc2trees:soursoptreesapling
    - pamhc2trees:starfruittreesapling
    - pamhc2trees:tamarindtreesapling
    - pamhc2trees:vanillabeantreesapling
    - pamhc2trees:walnuttreesapling